### ISSUE TITLE
Update paths to match new ext tree

### ISSUE THREAD

**Issue by tofutim** [loqu8/SQLitePCL.raw#1]
Under Main ln 4951, I have a default libPattern
```
            string libPattern = args.Length > 2 ? args[2] : string.Format("$which\\$platform\\$arch\\lib\\$lib");
```
but I have changed this pattern now. The new pattern will be $which\\lib\\$platform\\$arch\\$lib. Please verify that the affected csproj see the correct path.

![image](https://cloud.githubusercontent.com/assets/157766/21244217/729dd124-c2d1-11e6-866f-bb754281683f.png)

Incidentally, if you want to run gen_build.cs from Visual Studio you can, and it helps debugging. You will want to right-click on the gen_build project, and select Properties -> Debug. Then add Command line arguments and Working directory as follows:

![image](https://cloud.githubusercontent.com/assets/157766/21244189/4537d784-c2d1-11e6-8a14-50be9033c0f2.png)
#

**Comment by tofutim** [comment]
Check that the paths to ownCloud libs are correct.

For android, inspect SQLitePCLRaw.lib.xsqlite3.android.csproj (will get packed into dll)
For ios, inspect SQLitePCLRaw.lib.xsqlite3.ios_unified.static.csproj (will get packed into dll)
For windows, SQLitePCLRaw.lib.xsqlite3.windows.nuspec (loose in be an x86/ and x64/ folder)
For osx, SQLitePCLRaw.lib.xsqlite3.osx.nuspec (loose in main directory)
For uwp, mmm, I think I'm not done making that yet. See issue #2

**Comment by holland01** [comment]
Paths verified.

**Comment by tofutim** [comment]
Did you push changes?

**Comment by tofutim** [comment]
(or just write the libPattern into args?)

**Comment by holland01** [comment]
I haven't yet - doing so now.
