### ISSUE TITLE
UWP does not fetch NuGet package properly

### ISSUE THREAD

**Issue by holland01** [loqu8/SQLitePCL.raw#11]
Something different exists in gen_build.cs which is affecting this. In process of being diagnosed.

**Comment by holland01** [comment]
Interesting information [here](http://stackoverflow.com/a/36964558) (check the second `Q:` entry in the quote from the referenced article). 

I tried installing the bundle for e_sqlite3 and the same issue is occurring (when I said it worked this was with installing just the library portion - my mistake). ~~So, it looks like UWP just doesn't work with Netstandard period.~~ Hmm, actually this isn't right.

**Comment by holland01** [comment]
* It's important that `Microsoft.NETCore.UniversalWindowsPlatform` is at its latest version; mine was at 5.0 - the latest is AFAIK is 5.2.2. You can get the NuGet command from [here](https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/)

(you probably only want to try this next option if the above doesn't solve the issue).

* Install the .NET Core 1.1 x64 SDK, which you can find [here](https://www.microsoft.com/net/download/core#/current/sdk)

Installing the xsqlite3 bundle after that works.

_____

Installing the .NET Core 1.1 SDK is probably unnecessary. The NuGet link for `Microsoft.NETCore.UniversalWindowsPlatform` refers to dependencies which imply that System.* libraries <  version 4.0.11 will get pulled in if necessary, which was a core issue in one of the errors:

```
Version conflict detected for System.Collections. 
DbTest.Forms.UWP (>= 1.0.0) -> SQLitePCLRaw.core (>= 1.1.1) -> NETStandard.Library (>= 1.6.0) -> System.Collections (>= 4.0.11) 
DbTest.Forms.UWP (>= 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.0.0) -> Microsoft.NETCore.Runtime (>= 1.0.0) -> Microsoft.NETCore.Runtime.CoreCLR-arm (>= 1.0.0) -> System.Collections (= 4.0.10).
```

Another error which you'll probably see if your dependency versions are off is something like this:

 ```
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).
```

**Comment by tofutim** [comment]
Were you using Blank App (Universal Windows)?

I will install .NET Core 1.1 x64 SDK - actually I think I installed it with
'dotnet restore' on Team City

[image: Inline image 1]

**Comment by tofutim** [comment]
or were you doing something off of .NET Core?

**Comment by holland01** [comment]
Yeah, it was Blank App. I tried it on the DBTest though and it worked. You also have modify your project.json like so (just add the 5.2.2):

```
{
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
    "SQLitePCLRaw.bundle_xsqlite3": "1.1.2-pre20161219183256",
    "Xamarin.Forms": "2.0.0.6482"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

I'll merge my branch into develop, though. That way the config files are at least there.
